export default ({
  "airplane": "Avião",
  "bank": "Banco",
  "beach": "Praia",
  "broadway_theater": "Teatro",
  "casino": "Cassino",
  "cathedral": "Catedral",
  "circus_tent": "Circo",
  "corporate_party": "Festa da Empresa",
  "crusader_army": "Exército das Cruzadas",
  "day_spa": "SPA",
  "embassy": "Embaixada",
  "hospital": "Hospital",
  "hotel": "Hotel",
  "military_base": "Base Militar",
  "movie_studio": "Estúdio de Filmagem",
  "ocean_liner": "Cruzeiro Marítimo",
  "passenger_train": "Trem de Passageiros",
  "pirate_ship": "Navio Pirata",
  "polar_station": "Estação Polar",
  "police_station": "Delegacia de Polícia",
  "restaurant": "Restaurante",
  "school": "Escola",
  "service_station": "Oficina Mecânica",
  "space_station": "Estação Espacial",
  "submarine": "Submarino",
  "supermarket": "Supermercado",
  "university": "Faculdade"
})
